org.gradle.jvmargs=-Xmx1024m -Xss512k -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=96m -XX:ActiveProcessorCount=4 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseSerialGC -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
kotlin.daemon.jvmargs=-Xmx384m -Xss512k

